name: CI-macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.0.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test MacOS CI
      run: xcodebuild clean build test Projects/Apps/ViaCepApp/ViaCep.xcodeproj/ -scheme "ViaCep" -testPlan "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   