name: CI-macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.0.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install --project-directory=Projects/Apps/ViaCepApp/

    - name: Build and Test MacOS CI
      run: xcodebuild -project Projects/Apps/ViaCepApp/ViaCep.xcodeproj -scheme ViaCep
   